#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

# Per der_gabe's Server Fault answer <http://serverfault.com/a/670688>, in order to avoid
#
# ```
# dpkg-preconfigure: unable to re-open stdin: No such file or directory
# ```
#
# errors, make `dpkg-reconfigure` use the noninteractive frontend in order to avoid
export DEBIAN_FRONTEND=noninteractive

echo "==> Installing dependencies..."
echo "===> Installing kpartx, qemu-user-static, curl, and git packages..."
apt-get update >/dev/null
apt-get install --yes kpartx qemu-user-static curl git >/dev/null

echo "===> Installing Node.js v6.x..."
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - >/dev/null
apt-get install --yes nodejs >/dev/null

if [[ ! -d "/opt/jenny" ]]; then
  echo "===> Installing jenny..."
  git clone --quiet https://github.com/pincio/jenny.git /opt/jenny
  sh -c "cd /opt/jenny && npm install" >/dev/null
fi
